### ISSUE TITLE
duplicate of combined fields

### ISSUE THREAD

**Issue by mdidish** [tertek/redcap-unique-actiontag#10]
Hello
Thank you very much for this external module for REDCap.

My goal is to detect duplicate records based on multiple fields, e.g. last name, first name, and date of birth.

@UNIQUE="last name, first name, date_of_birth" detects duplicates even if only one of these three fields is similar to a previous record. Is there a solution?

Best,
Marc

**Comment by tertek** [comment]
Hi @mdidish do you have an example input where this case happens? I would like to check it.

**Comment by mdidish** [comment]
ok I think I had misinterpreted the @UNIQUE function with several arguments. Let's say I have three fields:
- "name": name of participant
- "surname": surname of participant
- "birthdate": date of birth of participant

If I indicate @unique="name, surname, birthdate" in TAG name field, I will have a warning of duplicate if I enter:
- Michel in name field, and I have a previous record with name="Michel"
- Michel in name field, and I have a previous record with surname="Michel"

In fact, what I would like, is to have a warning only if I have a previous record with identical name AND surname AND birthdate. Do you think is it possible?

**Comment by tertek** [comment]
I am not sure if this will work, but you can give it a try:

- make a calculated field "full_name" = "name" + "lastname"
- set @UNIQUE="full_name"

**Comment by mdidish** [comment]
I tried this, but I have no warning, it seems that @UNIQUE doesn't work on calculated field.

**Comment by tertek** [comment]
I have tried and it works:
![image](https://user-images.githubusercontent.com/75415872/151143034-4469f42d-fb85-4d68-97d4-7af062108b34.png)

You have to use:

`@CALCTEXT(concat([firstname], " ", [lastname])) @UNIQUE`

**Comment by mdidish** [comment]
I have also the warning duplicate message If I click in the merged fiel, specifically when I click somewhere else after clicking on the merged field (1/ I click on the merged fiel, 2/ I click on another field, 3/ I obtained the warning).

It looks like the CALCTEXT tag is applied in real time, but UNIQUE tag requires clicking on the field?

**Comment by tertek** [comment]
Please update your Module to the latest version if not.
Yes, UNIQUE is triggered after an interaction with the form.

**Comment by tertek** [comment]
You can enable "Hard Check" which will disable the "Save Button" after detecting the duplicate. This may partially solve your issue:

![image](https://user-images.githubusercontent.com/75415872/151149174-d291603a-6c25-43c9-bac0-f53714588c7e.png)

**Comment by mdidish** [comment]
"Enable Hard Check" does not solve the problem, the "Save Button" becomes disabled only if I click at least once on the merged field.

Do you think that in a future version, the UNIQUE action tag could be updated without action on the concerned field, as for CALCTEXT tag? In my case, users may not click on this merged field as they have no data to enter in this field.

Or, without a merged field, that this UNIQUE tag itself merges data from two fields and compares it to previous records?

**Comment by tertek** [comment]
Detecting changes in an calculated field (@CALCTEXT) when using together with @UNIQUE could be a feature to think of in the future. Unfortunately, I am not able to work on it in the next time. You may have to look for another way to resolve your case.
