### ISSUE TITLE
Adjust text messages and add translations

### ISSUE THREAD

**Issue by ThomasVermes** [tertek/redcap-unique-actiontag#4]
![image](https://user-images.githubusercontent.com/75424115/117780735-32828e00-b240-11eb-875c-6786137d35f9.png)

The warning's text has to be change:
"The field plf_imid is a unique field (@UNIQUE), dies muss über alle Einträge eindeutig sein. Ein anderer Eintrag **oder eine andere Visite im aktuellen Eintrag** hat bereits diesen Wert (123546) . Sie müssen diesen Wert ändern bevor Sie fortfahren können."

The action tag work as it should. It prevent that the plf_imid variable contains already used imid between records.
Within a record and between events, the same id is possible (and it is correct so). Therefore, what underlined in bold in the worning has to be deleted

**Comment by tertek** [comment]
I have not optimized any of the texts yet. I am using the same texts that were used for "secondary primary key". So actually these need to be re-written and translated. Would you like to help me with that?

**Comment by ThomasVermes** [comment]
for that warning I would just delete "oder eine andere Visite im aktuellen Eintrag"

**Comment by tertek** [comment]
I will add a new update soon.
To achieve this Javascript Translation Support has to be added:

1) Add new function `addJSLangSupport()` to `renderActionTag()`
```php
     $module->initializeJavascriptModuleObject();
     $module->tt_transferToJavascriptModuleObject();
```
2) Add module to js params within `renderJavacript()`:
```php
?>
var module = <?=$this->getJavascriptModuleObjectName()?>;
<?php
```
3) Update Language file(s)
Add English and German versions

**Comment by tertek** [comment]
Done
