### ISSUE TITLE
Data Entry Mode: Save Button still enabled when non-uniqueness detected

### ISSUE THREAD

**Issue by jouterleys** [tertek/redcap-unique-actiontag#5]
Do the action tags only work in Data Entry mode?

When using @UNIQUE or @UNIQUE-STRICT I am still able to save data with no notification in Survey Mode despite non-unique entry.

**Comment by tertek** [comment]
Yes, but as has been requested from other sides, I have added it as a feature request (https://github.com/tertek/redcap-unique-actiontag/issues/6)

I am checking the Save Button issue. As far as I remember it should be blurred, but was implemented a bit dirty. I may add proper support for that as well. Thanks for the issue!

**Comment by tertek** [comment]
https://github.com/tertek/redcap-unique-actiontag/issues/7
